const express=require('express'),crypto=require('node:crypto'),path=require('node:path'),fs=require('node:fs');
const{Pool}=require('pg');
const app=express(),PORT=Number(process.env.PORT||3000),BASE=(process.env.PUBLIC_URL||`http://localhost:${PORT}`).replace(/\/$/,''),pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:undefined});
const puzzles=require('./puzzles.json'),rounds=new Map(),streams=new Map(),oauth=new Map(),commandTimes=new Map();
const KICK_KEY=`-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq/+l1WnlRrGSolDMA+A8\n6rAhMbQGmQ2SapVcGM3zq8ANXjnhDWocMqfWcTd95btDydITa10kDvHzw9WQOqp2\nMZI7ZyrfzJuz5nhTPCiJwTwnEtWft7nV14BYRDHvlfqPUaZ+1KR4OCaO/wWIk/rQ\nL/TjY0M70gse8rlBkbo2a8rKhu69RQTRsoaf4DVhDPEeSeI5jVrRDGAMGL3cGuyY\n6CLKGdjVEM78g3JfYOvDU/RvfqD7L89TZ3iN94jrmWdGz34JNlEI5hqK8dd7C5EF\nBEbZ5jgB8s8ReQV8H+MkuffjdAj3ajDDX3DOJMIut1lBrUVD1AaSrGCKHooWoL2e\ntwIDAQAB\n-----END PUBLIC KEY-----`;
const hash=value=>crypto.createHash('sha256').update(value).digest('hex'),token=(n=32)=>crypto.randomBytes(n).toString('base64url'),norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\b(the|a|an)\b/g,' ').replace(/\s+/g,' ').trim();
const roundDurationMs=round=>round.isJackpot?60000:['hard','expert'].includes(String(round.difficulty).toLowerCase())?45000:30000;
function encrypt(value){if(!process.env.TOKEN_ENCRYPTION_KEY)throw new Error('TOKEN_ENCRYPTION_KEY is required');const key=crypto.createHash('sha256').update(process.env.TOKEN_ENCRYPTION_KEY).digest(),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),data]).toString('base64')}
function cookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
async function tenantBySession(req){const t=cookies(req).emoji_session;if(!t)return null;return(await pool.query('SELECT * FROM tenants WHERE session_token_hash=$1',[hash(t)])).rows[0]||null}
async function tenantByOverlay(value){return(await pool.query('SELECT * FROM tenants WHERE overlay_token=$1',[value])).rows[0]||null}
async function scores(id,period='weekly'){const start=period==='daily'?"NOW()-INTERVAL '1 day'":period==='alltime'?null:"date_trunc('week',NOW())";if(!start)return(await pool.query('SELECT username,points,wins,streak,best_streak AS "bestStreak",correct,wrong FROM scores WHERE tenant_id=$1 ORDER BY points DESC,wins DESC LIMIT 10',[id])).rows;return(await pool.query(`SELECT username,SUM(points)::int points,SUM(CASE WHEN placement=1 THEN 1 ELSE 0 END)::int wins,0 streak,MAX(placement)::int AS "bestStreak",COUNT(*)::int correct,0 wrong FROM score_events WHERE tenant_id=$1 AND won_at>=${start} GROUP BY user_key,username ORDER BY points DESC,wins DESC LIMIT 10`,[id])).rows}
async function state(tenant){const round=rounds.get(tenant.id)||null,game=round&&round.status!=='idle'?round:null;return{tenant:{channel:tenant.channel_name,displayName:tenant.display_name},round:game&&{id:game.id,status:game.status,category:game.category,emojis:game.emojis,difficulty:game.difficulty,startedAt:game.startedAt,endsAt:game.endsAt,winner:game.winner,correctAnswers:game.correctAnswers,answer:game.status==='finished'?game.answers[0]:null,isJackpot:game.isJackpot},scores:await scores(tenant.id,'weekly'),scoreboard:{visible:Boolean(round?.scoreboardUntil>Date.now()),shownBy:round?.scoreboardBy||null,hideAt:round?.scoreboardUntil||0,period:round?.scoreboardPeriod||'weekly'},scoreboardScores:await scores(tenant.id,round?.scoreboardPeriod||'weekly'),rankCard:{visible:false},jackpot:{points:tenant.jackpot,chance:.2},challenge:{name:'Crowd Solver',description:'Get 10 correct viewers in one round',target:10,progress:game?.correctAnswers?.length||0,doublePointsActive:false,doublePointsUntil:0},badgeAlert:{visible:false},overlayQueue:{length:0,max:5,active:false},auto:{nextRollAt:Number(tenant.next_round_at||Date.now()+900000),missedRolls:0},config:{roundMs:game?roundDurationMs(game):30000,autoChance:.7,maxMissedRolls:3,resultsMs:10000},recentMessages:[]}}
async function push(tenant){const packet=`data: ${JSON.stringify(await state(tenant))}\n\n`;for(const res of streams.get(tenant.id)||[])res.write(packet)}
async function startRound(tenant){if(rounds.get(tenant.id)?.status==='open')return;const p=puzzles[Math.floor(Math.random()*puzzles.length)],now=Date.now(),round={...p,status:'open',startedAt:now,winner:null,correctAnswers:[],users:new Set(),attempts:new Map(),isJackpot:Math.random()<.2},duration=roundDurationMs(round);round.endsAt=now+duration;rounds.set(tenant.id,round);await pool.query('UPDATE tenants SET next_round_at=$2 WHERE id=$1',[tenant.id,now+900000]);setTimeout(()=>finishRound(tenant),duration);await push(tenant)}
async function finishRound(tenant){const r=rounds.get(tenant.id);if(!r||r.status!=='open')return;r.status='finished';if(!r.winner){tenant.jackpot+=100;await pool.query('UPDATE tenants SET jackpot=$2 WHERE id=$1',[tenant.id,tenant.jackpot])}await push(tenant);setTimeout(async()=>{rounds.delete(tenant.id);await push(tenant)},10000)}
async function message(tenant,user,content,userId){const r=rounds.get(tenant.id),cmd=String(content).trim().toLowerCase().split(/\s+/);if(cmd[0]==='!scoreboard'){if(!r)rounds.set(tenant.id,{status:'idle',correctAnswers:[],scoreboardUntil:Date.now()+12000,scoreboardBy:user,scoreboardPeriod:['daily','alltime'].includes(cmd[1])?cmd[1]:'weekly'});else{r.scoreboardUntil=Date.now()+12000;r.scoreboardBy=user;r.scoreboardPeriod=['daily','alltime'].includes(cmd[1])?cmd[1]:'weekly'}await push(tenant);return}if(!r||r.status!=='open'||Date.now()>r.endsAt)return;const key=`kick:${userId||user.toLowerCase()}`;if(r.users.has(key))return;const attempt=r.attempts.get(key)||{wrong:0,locked:0};if(Date.now()<attempt.locked)return;if(!r.answers.some(a=>norm(a)===norm(content))){attempt.wrong++;attempt.locked=Date.now()+4000;r.attempts.set(key,attempt);return}const placement=r.correctAnswers.length+1,mult=placement===1?1:placement===2?.7:placement===3?.5:.25,responseMs=Date.now()-r.startedAt,base={easy:100,medium:150,hard:225,expert:350}[r.difficulty],regular=Math.max(10,Math.round((base+Math.max(0,75-Math.floor(responseMs/200))-attempt.wrong*10)*mult)),bonus=r.isJackpot&&placement===1?tenant.jackpot:0,points=regular+bonus;r.users.add(key);const answer={username:user,placement,points,responseMs,multiplier:mult,jackpotBonus:bonus};r.correctAnswers.push(answer);if(placement===1){r.winner=answer;if(bonus){tenant.jackpot=250;await pool.query('UPDATE tenants SET jackpot=250 WHERE id=$1',[tenant.id])}}await pool.query(`INSERT INTO scores(tenant_id,user_key,username,points,wins,streak,best_streak,correct,updated_at) VALUES($1,$2,$3,$4,$5,1,1,1,NOW()) ON CONFLICT(tenant_id,user_key) DO UPDATE SET username=$3,points=scores.points+$4,wins=scores.wins+$5,streak=scores.streak+1,best_streak=GREATEST(scores.best_streak,scores.streak+1),correct=scores.correct+1,updated_at=NOW()`,[tenant.id,key,user,points,placement===1?1:0]);await pool.query('INSERT INTO score_events(tenant_id,user_key,username,points,placement) VALUES($1,$2,$3,$4,$5)',[tenant.id,key,user,points,placement]);await push(tenant)}
function verify(req,raw){const id=req.headers['kick-event-message-id'],ts=req.headers['kick-event-message-timestamp'],sig=req.headers['kick-event-signature'];if(!id||!ts||!sig)return false;const v=crypto.createVerify('RSA-SHA256');v.update(`${id}.${ts}.${raw}`);v.end();return v.verify(KICK_KEY,Buffer.from(sig,'base64'))}
app.use('/webhooks/kick',express.raw({type:'application/json',limit:'100kb'}));app.use(express.urlencoded({extended:false}));app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
app.get('/healthz',(_,res)=>res.json({ok:true}));
app.get('/',async(req,res)=>{const t=await tenantBySession(req);res.redirect(t?'/dashboard':'/join')});
app.get('/join',(_,res)=>res.send(page('Join the private beta',`<form method="post"><label>Invite code<input name="invite" required></label><label>Kick channel<input name="channel" required></label><label>Display name<input name="display" required></label><button>Join beta</button></form>`)));
app.post('/join',async(req,res)=>{const codes=String(process.env.INVITE_CODES||'').split(',').map(x=>x.trim()).filter(Boolean);if(!codes.includes(req.body.invite))return res.status(403).send(page('Invite required','<p>That invite code is not valid.</p>'));const session=token(),id=crypto.randomUUID(),overlay=token();try{await pool.query('INSERT INTO tenants(id,channel_name,display_name,overlay_token,session_token_hash,next_round_at) VALUES($1,$2,$3,$4,$5,$6)',[id,norm(req.body.channel).replace(/ /g,''),String(req.body.display).slice(0,40),overlay,hash(session),Date.now()+900000]);res.setHeader('Set-Cookie',`emoji_session=${session}; HttpOnly; ${process.env.NODE_ENV==='production'?'Secure; ':''}SameSite=Lax; Path=/; Max-Age=2592000`);res.redirect('/dashboard')}catch(e){res.status(400).send(page('Could not join','<p>Channel already registered or input invalid.</p>'))}});
app.get('/dashboard',async(req,res)=>{const t=await tenantBySession(req);if(!t)return res.redirect('/join');const root=`${BASE}/o/${t.overlay_token}`,overlay=`${root}/overlay.html`,scoreboard=`${root}/scoreboard.html`;res.send(page(`${escapeHtml(t.display_name)} dashboard`,`<div class="status">${t.kick_access_token?'✓ Kick connected':'○ Connect Kick to start'}</div><a class="button" href="/auth/kick">${t.kick_access_token?'Reconnect Kick':'Connect Kick'}</a><h2>OBS Browser Sources</h2>${copy('Game overlay',overlay)}${copy('Scoreboard',scoreboard)}<button class="secondary" onclick="navigator.clipboard.writeText('Game overlay: ${overlay}\\nScoreboard: ${scoreboard}');this.textContent='✓ Both copied';setTimeout(()=>this.textContent='Copy both URLs',1800)">Copy both URLs</button><p>Add both at 1920 × 1080 and keep Scoreboard above Overlay.</p><a class="button" href="${root}/test" target="_blank">Test overlay</a><section class="guide"><span class="pill">CLOUD SETUP</span><h2>Install in OBS</h2><p class="muted">Nothing else needs to be installed on your computer—only OBS Studio is required.</p><ol><li>Open <b>OBS Studio</b> and select your streaming scene.</li><li>Under <b>Sources</b>, click <b>+</b>, then choose <b>Browser</b>.</li><li>Name it <b>Emoji Decoder Overlay</b>.</li><li>Copy the <b>Game overlay</b> URL above and paste it into OBS.</li><li>Set Width to <b>1920</b> and Height to <b>1080</b>.</li><li>Repeat those steps with the <b>Scoreboard</b> URL.</li><li>In the Sources list, place <b>Scoreboard above Game Overlay</b>.</li><li>Return here and click <b>Test overlay</b> to run a private test round.</li><li>Adjust the sources if needed. Testing does not start your stream.</li></ol></section>`))});
app.get('/auth/kick',async(req,res)=>{const t=await tenantBySession(req);if(!t)return res.redirect('/join');const verifier=token(48),challenge=crypto.createHash('sha256').update(verifier).digest('base64url'),s=token(24);oauth.set(s,{tenant:t.id,verifier,expires:Date.now()+600000});const q=new URLSearchParams({response_type:'code',client_id:process.env.KICK_CLIENT_ID,redirect_uri:`${BASE}/auth/kick/callback`,scope:'events:subscribe',code_challenge:challenge,code_challenge_method:'S256',state:s});res.redirect(`https://id.kick.com/oauth/authorize?${q}`)});
app.get('/auth/kick/callback',async(req,res)=>{const a=oauth.get(req.query.state);if(!a||a.expires<Date.now())return res.status(400).send('OAuth expired');oauth.delete(req.query.state);const response=await fetch('https://id.kick.com/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:process.env.KICK_CLIENT_ID,client_secret:process.env.KICK_CLIENT_SECRET,redirect_uri:`${BASE}/auth/kick/callback`,code_verifier:a.verifier,code:req.query.code})}),tokens=await response.json();if(!response.ok)return res.status(400).json(tokens);await pool.query('UPDATE tenants SET kick_access_token=$2,kick_refresh_token=$3,kick_token_expires_at=$4 WHERE id=$1',[a.tenant,encrypt(tokens.access_token),tokens.refresh_token?encrypt(tokens.refresh_token):null,Date.now()+Number(tokens.expires_in||3600)*1000]);const sub=await fetch('https://api.kick.com/public/v1/events/subscriptions',{method:'POST',headers:{Authorization:`Bearer ${tokens.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({method:'webhook',events:[{name:'chat.message.sent',version:1}]})});if(!sub.ok)return res.status(400).send(`Kick connected, subscription failed: ${await sub.text()}`);res.redirect('/dashboard')});
app.post('/webhooks/kick',async(req,res)=>{const raw=req.body.toString('utf8');if(!verify(req,raw))return res.sendStatus(403);const id=req.headers['kick-event-message-id'];try{await pool.query('INSERT INTO webhook_messages(message_id) VALUES($1)',[id])}catch{return res.json({duplicate:true})}const e=JSON.parse(raw),channel=norm(e.broadcaster?.username||e.broadcaster?.user_name||'').replace(/ /g,''),t=(await pool.query('SELECT * FROM tenants WHERE channel_name=$1',[channel])).rows[0];if(t&&req.headers['kick-event-type']==='chat.message.sent')await message(t,e.sender.username,e.content,e.sender.user_id);res.json({received:true})});
app.get('/o/:token/events',async(req,res)=>{const t=await tenantByOverlay(req.params.token);if(!t)return res.sendStatus(404);res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});if(!streams.has(t.id))streams.set(t.id,new Set());streams.get(t.id).add(res);res.write(`data: ${JSON.stringify(await state(t))}\n\n`);req.on('close',()=>streams.get(t.id)?.delete(res))});
app.get('/o/:token/state',async(req,res)=>{const t=await tenantByOverlay(req.params.token);if(!t)return res.sendStatus(404);res.json(await state(t))});
app.get('/o/:token/overlay.html',async(req,res)=>{if(!await tenantByOverlay(req.params.token))return res.sendStatus(404);res.sendFile(path.join(__dirname,'public','overlay.html'))});
app.get('/o/:token/scoreboard.html',async(req,res)=>{if(!await tenantByOverlay(req.params.token))return res.sendStatus(404);res.sendFile(path.join(__dirname,'public','scoreboard.html'))});
app.get('/o/:token/test',async(req,res)=>{const t=await tenantByOverlay(req.params.token);if(!t)return res.sendStatus(404);await startRound(t);res.redirect(`/o/${t.overlay_token}/overlay.html`)});
setInterval(async()=>{const due=(await pool.query('SELECT * FROM tenants WHERE kick_access_token IS NOT NULL AND COALESCE(next_round_at,0)<=$1',[Date.now()])).rows;for(const t of due)await startRound(t)},30000);
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function copy(label,value){return`<div class="copy"><b>${label}</b><code>${value}</code><button onclick="navigator.clipboard.writeText('${value}')">Copy</button></div>`}function page(title,body){return`<!doctype html><meta name="viewport" content="width=device-width"><title>${title}</title><style>body{margin:0;background:#070a08;color:#fff;font:16px system-ui}main{max-width:820px;margin:50px auto;padding:28px}h1{font-size:42px}h1,h2{color:#fff}.status,.copy,form,.guide{padding:18px;margin:14px 0;border:1px solid #334238;border-radius:14px;background:#101712}.status{color:#53fc18;font-weight:800}label{display:grid;gap:7px;margin:14px 0}input{padding:13px;border:1px solid #415045;border-radius:9px;background:#080b09;color:#fff}.button,button{display:inline-block;padding:12px 16px;border:0;border-radius:9px;background:#53fc18;color:#071006;font-weight:900;text-decoration:none;cursor:pointer}.secondary{margin-left:8px;background:#253029;color:#fff}.copy{display:grid;grid-template-columns:130px 1fr auto;gap:12px;align-items:center}.copy code{overflow:hidden;text-overflow:ellipsis;color:#b7c5bb}.guide{margin-top:28px;padding:26px}.guide h2{font-size:27px;margin:10px 0 4px}.guide ol{padding-left:25px}.guide li{margin:12px 0;line-height:1.5}.muted{color:#9cab9f}.pill{display:inline-flex;padding:5px 10px;border-radius:99px;background:#253029;color:#53fc18;font-size:12px;font-weight:800;letter-spacing:.08em}@media(max-width:650px){.copy{grid-template-columns:1fr}main{margin:10px}.secondary{margin:10px 0 0}}</style><main><small style="color:#53fc18;letter-spacing:.18em">EMOJI DECODER CLOUD BETA</small><h1>${title}</h1>${body}</main>`}
pool.query(fs.readFileSync(path.join(__dirname,'schema.sql'),'utf8')).then(()=>app.listen(PORT,'0.0.0.0',()=>console.log(`Cloud beta listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
